name: mvp_assessement
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  firebase_auth: ^1.3.0
  firebase_core: ^1.2.1
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.0
  flutter_modular: ^3.2.2+1
  google_sign_in: ^5.0.4
  mobx: ^2.0.1


  

dev_dependencies:
  build_runner: ^2.0.4
  mobx_codegen: ^2.0.1+3
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true